# Generated by Django 3.1.3 on 2020-11-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qv1', '0004_auto_20201117_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_id',
        ),
    ]
